import axios from 'axios';

const apiKey = 'AIzaSyDAxr105yD51msIM-HUUVcWnhvPGSOf2U0';
const playlistId = 'PLRnlRGar-_296KTsVL0R6MEbpwJzD8ppA';
const videoId= 'UIwqE3eBEos'
/*
async function getVideoInfo(videoId) {
  try {
    const response = await axios.get('https://www.googleapis.com/youtube/v3/videos', {
      params: {
        part: 'snippet',
        id: videoId,
        key: apiKey,
      },
    });

    if (response.data.items && response.data.items.length > 0) {
      const videoInfo = response.data.items[0].snippet;
      console.log('Información del Video:');
      console.log(`Título: ${videoInfo.title}`);
      console.log(`Descripción: ${videoInfo.description}`);
      console.log(`Fecha de Publicación: ${videoInfo.publishedAt}`);
      console.log(`Thumbnail: ${videoInfo.thumbnails.default.url}`);
    } else {
      console.log(`No se encontró información para el video con ID: ${videoId}`);
    }
  } catch (error) {
    console.error('Error al obtener información del video:', error.message);
  }
}
*/

/*
// Obtener lista de videos de la playlist
axios.get('https://www.googleapis.com/youtube/v3/playlistItems', {
  params: {
    part: 'snippet',
    playlistId: playlistId,
    key: apiKey,
    maxResults: 10,
  },
})
  .then(async (response) => {
    const videos = response.data.items;

    if (videos.length >= 3) {
      // Obtener información detallada del tercer video en la lista
      const thirdVideoId = videos[2].snippet.resourceId.videoId;
      console.log(`Título del Tercer Video: ${videos[2].snippet.title}`);
      console.log(`ID del Tercer Video: ${thirdVideoId}`);

      // Obtener transcripción del video
      await getTranscriptionInfo(thirdVideoId);
    } else {
      console.log('La lista de videos no contiene al menos 3 elementos.');
    }
  })
  .catch((error) => {
    // Manejar errores
    console.error(error);
  });

*/

async function getTranscriptionInfo(videoId) {
    console.log("Entrando a captions")
  try {
    const response = await axios.get('https://www.googleapis.com/youtube/v3/captions', {
      params: {
        part: 'snippet',
        videoId: videoId,
        key: apiKey,
      },
    });

    if (response.data.items && response.data.items.length > 0) {
      console.log("Datos:", response.data.items[0]);
    
      
      response.data.items.forEach(item => {
        const language = item.snippet.language;
        const isAutoGenerated = item.snippet.isAutoSynced;
        const transcription = item.snippet.body;
        // Corregir aquí
        console.log(`Idioma: ${language}, Generado automáticamente: ${isAutoGenerated}`);
        console.log(`Transcripción: ${transcription}`);
        
      });

      /*
      'https://youtube.googleapis.com/youtube/v3/captions/AUieDaYcV_mXPMPMe-Uu1O8bw6EURvgQWKsqrzjbBfMCr76Z8RA?key=[AIzaSyDAxr105yD51msIM-HUUVcWnhvPGSOf2U0]' \
        --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
        --header 'Accept: application/json' \
        --compressed */
    } else {
      console.log(`El video ${videoId} no tiene transcripciones disponibles.`);
    }
  } catch (error) {
    // Manejar errores
    console.error('Error al obtener información de transcripciones:', error.message);
  }
}

getTranscriptionInfo(videoId);